# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      -  id: bandit
         name: bandit
         stages: [commit]
         entry: bandit
         args: ["--recursive", "--exclude", "**/*test.py"]
         language: system
         types: [python]

      -  id: isort
         name: isort
         stages: [commit]
         entry: isort
         args: ["--check-only", "integration_test"]
         language: system
         types: [python]

      -  id: black
         name: black
         stages: [commit]
         entry: black
         args: ["--check"]
         language: system
         types: [python]

      -  id: flake8
         name: flake8
         stages: [commit]
         entry: flake8
         args: ["google_foobar"]
         language: python
         types: [python]

      -  id: mypy
         name: mypy
         stages: [commit]
         entry: make mypy
         language: system
         types: [python]

      -  id: pylint
         name: pylint
         stages: [commit]
         entry: pylint
         args: ["google_foobar", "--disable=duplicate-code"]
         language: system
         types: [python]

      -  id: pydocstyle
         name: pydocstyle
         stages: [commit]
         entry: pydocstyle
         args: ["google_foobar"]
         language: system
         types: [python]
